interface SeedCountry {
    name: string;
    id: string;
  }
  
export const countries: SeedCountry[] = [
    { name: "Afganistán", id: "AF" },
    { name: "Islas Åland", id: "AX" },
    { name: "Albania", id: "AL" },
    { name: "Argelia", id: "DZ" },
    { name: "Samoa Americana", id: "AS" },
    { name: "Andorra", id: "AD" },
    { name: "Angola", id: "AO" },
    { name: "Anguila", id: "AI" },
    { name: "Antártida", id: "AQ" },
    { name: "Antigua y Barbuda", id: "AG" },
    { name: "Argentina", id: "AR" },
    { name: "Armenia", id: "AM" },
    { name: "Aruba", id: "AW" },
    { name: "Australia", id: "AU" },
    { name: "Austria", id: "AT" },
    { name: "Azerbaiyán", id: "AZ" },
    { name: "Bahamas", id: "BS" },
    { name: "Baréin", id: "BH" },
    { name: "Bangladesh", id: "BD" },
    { name: "Barbados", id: "BB" },
    { name: "Bielorrusia", id: "BY" },
    { name: "Bélgica", id: "BE" },
    { name: "Belice", id: "BZ" },
    { name: "Benín", id: "BJ" },
    { name: "Bermudas", id: "BM" },
    { name: "Bután", id: "BT" },
    { name: "Bolivia", id: "BO" },
    { name: "Bosnia y Herzegovina", id: "BA" },
    { name: "Botsuana", id: "BW" },
    { name: "Isla Bouvet", id: "BV" },
    { name: "Brasil", id: "BR" },
    { name: "Territorio Británico del Océano Índico", id: "IO" },
    { name: "Brunéi", id: "BN" },
    { name: "Bulgaria", id: "BG" },
    { name: "Burkina Faso", id: "BF" },
    { name: "Burundi", id: "BI" },
    { name: "Camboya", id: "KH" },
    { name: "Camerún", id: "CM" },
    { name: "Canadá", id: "CA" },
    { name: "Cabo Verde", id: "CV" },
    { name: "Islas Caimán", id: "KY" },
    { name: "República Centroafricana", id: "CF" },
    { name: "Chad", id: "TD" },
    { name: "Chile", id: "CL" },
    { name: "China", id: "CN" },
    { name: "Isla de Navidad", id: "CX" },
    { name: "Islas Cocos (Keeling)", id: "CC" },
    { name: "Colombia", id: "CO" },
    { name: "Comoras", id: "KM" },
    { name: "Congo", id: "CG" },
    { name: "Congo, República Democrática del", id: "CD" },
    { name: "Islas Cook", id: "CK" },
    { name: "Costa Rica", id: "CR" },
    { name: "Costa de Marfil", id: "CI" },
    { name: "Croacia", id: "HR" },
    { name: "Cuba", id: "CU" },
    { name: "Chipre", id: "CY" },
    { name: "República Checa", id: "CZ" },
    { name: "Dinamarca", id: "DK" },
    { name: "Yibuti", id: "DJ" },
    { name: "Dominica", id: "DM" },
    { name: "República Dominicana", id: "DO" },
    { name: "Ecuador", id: "EC" },
    { name: "Egipto", id: "EG" },
    { name: "El Salvador", id: "SV" },
    { name: "Guinea Ecuatorial", id: "GQ" },
    { name: "Eritrea", id: "ER" },
    { name: "Estonia", id: "EE" },
    { name: "Etiopía", id: "ET" },
    { name: "Islas Malvinas", id: "FK" },
    { name: "Islas Faroe", id: "FO" },
    { name: "Fiyi", id: "FJ" },
    { name: "Finlandia", id: "FI" },
    { name: "Francia", id: "FR" },
    { name: "Guayana Francesa", id: "GF" },
    { name: "Polinesia Francesa", id: "PF" },
    { name: "Territorios Australes Franceses", id: "TF" },
    { name: "Gabón", id: "GA" },
    { name: "Gambia", id: "GM" },
    { name: "Georgia", id: "GE" },
    { name: "Alemania", id: "DE" },
    { name: "Ghana", id: "GH" },
    { name: "Gibraltar", id: "GI" },
    { name: "Grecia", id: "GR" },
    { name: "Groenlandia", id: "GL" },
    { name: "Granada", id: "GD" },
    { name: "Guadalupe", id: "GP" },
    { name: "Guam", id: "GU" },
    { name: "Guatemala", id: "GT" },
    { name: "Guernsey", id: "GG" },
    { name: "Guinea", id: "GN" },
    { name: "Guinea-Bisáu", id: "GW" },
    { name: "Guyana", id: "GY" },
    { name: "Haití", id: "HT" },
    { name: "Islas Heard y McDonald", id: "HM" },
    { name: "Santa Sede (Ciudad del Vaticano)", id: "VA" },
    { name: "Honduras", id: "HN" },
    { name: "Hong Kong", id: "HK" },
    { name: "Hungría", id: "HU" },
    { name: "Islandia", id: "IS" },
    { name: "India", id: "IN" },
    { name: "Indonesia", id: "ID" },
    { name: "Irán", id: "IR" },
    { name: "Irak", id: "IQ" },
    { name: "Irlanda", id: "IE" },
    { name: "Isla de Man", id: "IM" },
    { name: "Israel", id: "IL" },
    { name: "Italia", id: "IT" },
    { name: "Jamaica", id: "JM" },
    { name: "Japón", id: "JP" },
    { name: "Jersey", id: "JE" },
    { name: "Jordania", id: "JO" },
    { name: "Kazajistán", id: "KZ" },
    { name: "Kenia", id: "KE" },
    { name: "Kiribati", id: "KI" },
    { name: "Corea del Norte", id: "KP" },
    { name: "Corea del Sur", id: "KR" },
    { name: "Kuwait", id: "KW" },
    { name: "Kirguistán", id: "KG" },
    { name: "Laos", id: "LA" },
    { name: "Letonia", id: "LV" },
    { name: "Líbano", id: "LB" },
    { name: "Lesoto", id: "LS" },
    { name: "Liberia", id: "LR" },
    { name: "Libia", id: "LY" },
    { name: "Liechtenstein", id: "LI" },
    { name: "Lituania", id: "LT" },
    { name: "Luxemburgo", id: "LU" },
    { name: "Macao", id: "MO" },
    { name: "Macedonia del Norte", id: "MK" },
    { name: "Madagascar", id: "MG" },
    { name: "Malawi", id: "MW" },
    { name: "Malasia", id: "MY" },
    { name: "Maldivas", id: "MV" },
    { name: "Malí", id: "ML" },
    { name: "Malta", id: "MT" },
    { name: "Islas Malvinas", id: "FK" },
    { name: "Islas Marianas del Norte", id: "MP" },
    { name: "Mauricio", id: "MU" },
    { name: "Mauritania", id: "MR" },
    { name: "México", id: "MX" },
    { name: "Micronesia", id: "FM" },
    { name: "Mónaco", id: "MC" },
    { name: "Mongolia", id: "MN" },
    { name: "Montenegro", id: "ME" },
    { name: "Montserrat", id: "MS" },
    { name: "Marruecos", id: "MA" },
    { name: "Mozambique", id: "MZ" },
    { name: "Myanmar", id: "MM" },
    { name: "Namibia", id: "NA" },
    { name: "Nauru", id: "NR" },
    { name: "Nepal", id: "NP" },
    { name: "Nicaragua", id: "NI" },
    { name: "Níger", id: "NE" },
    { name: "Nigeria", id: "NG" },
    { name: "Niue", id: "NU" },
    { name: "Norfolk", id: "NF" },
    { name: "Noruega", id: "NO" },
    { name: "Omán", id: "OM" },
    { name: "Pakistán", id: "PK" },
    { name: "Palaos", id: "PW" },
    { name: "Panamá", id: "PA" },
    { name: "Papúa Nueva Guinea", id: "PG" },
    { name: "Paraguay", id: "PY" },
    { name: "Perú", id: "PE" },
    { name: "Filipinas", id: "PH" },
    { name: "Pitcairn", id: "PN" },
    { name: "Polonia", id: "PL" },
    { name: "Portugal", id: "PT" },
    { name: "Puerto Rico", id: "PR" },
    { name: "Qatar", id: "QA" },
    { name: "Reino Unido", id: "GB" },
    { name: "Rumanía", id: "RO" },
    { name: "Rusia", id: "RU" },
    { name: "Ruanda", id: "RW" },
    { name: "San Bartolomé", id: "BL" },
    { name: "San Cristóbal y Nieves", id: "KN" },
    { name: "San Marino", id: "SM" },
    { name: "San Pedro y Miquelón", id: "PM" },
    { name: "San Tomé y Príncipe", id: "ST" },
    { name: "San Vicente y las Granadinas", id: "VC" },
    { name: "Santa Lucía", id: "LC" },
    { name: "Santo Tomé y Príncipe", id: "ST" },
    { name: "Senegal", id: "SN" },
    { name: "Serbia", id: "RS" },
    { name: "Seychelles", id: "SC" },
    { name: "Sierra Leona", id: "SL" },
    { name: "Singapur", id: "SG" },
    { name: "Sint Maarten", id: "SX" },
    { name: "Siria", id: "SY" },
    { name: "Somalia", id: "SO" },
    { name: "Sri Lanka", id: "LK" },
    { name: "Suazilandia", id: "SZ" },
    { name: "Sudán", id: "SD" },
    { name: "Suecia", id: "SE" },
    { name: "Suiza", id: "CH" },
    { name: "Surinam", id: "SR" },
    { name: "Svalbard y Jan Mayen", id: "SJ" },
    { name: "Tailandia", id: "TH" },
    { name: "Timor Oriental", id: "TL" },
    { name: "Togo", id: "TG" },
    { name: "Tokelau", id: "TK" },
    { name: "Tonga", id: "TO" },
    { name: "Trinidad y Tobago", id: "TT" },
    { name: "Túnez", id: "TN" },
    { name: "Turcas y Caicos", id: "TC" },
    { name: "Turquía", id: "TR" },
    { name: "Tuvalu", id: "TV" },
    { name: "Ucrania", id: "UA" },
    { name: "Uganda", id: "UG" },
    { name: "Uruguay", id: "UY" },
    { name: "Uzbekistán", id: "UZ" },
    { name: "Vanuatu", id: "VU" },
    { name: "Venezuela", id: "VE" },
    { name: "Vietnam", id: "VN" },
    { name: "Wallis y Futuna", id: "WF" },
    { name: "Yemen", id: "YE" },
    { name: "Yibuti", id: "DJ" },
    { name: "Zambia", id: "ZM" },
    { name: "Zimbabue", id: "ZW" },
  ];
  